import type { Certificate, Alert, RenewalJob, FleetStats } from '../types';

const now = new Date();

function daysFromNow(days: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() + days);
  return d.toISOString();
}

function daysAgo(days: number): string {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  return d.toISOString();
}

export const certificates: Certificate[] = [
  {
    id: 'cert-001',
    domain: 'api.acmecorp.io',
    status: 'healthy',
    provider: 'letsencrypt',
    server: 'nginx',
    challenge: 'http-01',
    isWildcard: false,
    expiresAt: daysFromNow(72),
    issuedAt: daysAgo(18),
    renewsAt: daysFromNow(42),
    daysUntilExpiry: 72,
    chain: [
      { subject: 'api.acmecorp.io', issuer: 'R3', valid: true },
      { subject: 'R3', issuer: 'ISRG Root X1', valid: true },
      { subject: 'ISRG Root X1', issuer: 'ISRG Root X1', valid: true },
    ],
    sans: [
      { value: 'api.acmecorp.io', covered: true },
      { value: 'www.api.acmecorp.io', covered: true },
    ],
    ocspStapling: true,
    autoRenewal: true,
    lastScanned: daysAgo(1),
    lastRepaired: null,
  },
  {
    id: 'cert-002',
    domain: '*.acmecorp.io',
    status: 'healthy',
    provider: 'letsencrypt',
    server: 'nginx',
    challenge: 'dns-01',
    isWildcard: true,
    expiresAt: daysFromNow(55),
    issuedAt: daysAgo(35),
    renewsAt: daysFromNow(25),
    daysUntilExpiry: 55,
    chain: [
      { subject: '*.acmecorp.io', issuer: 'R3', valid: true },
      { subject: 'R3', issuer: 'ISRG Root X1', valid: true },
      { subject: 'ISRG Root X1', issuer: 'ISRG Root X1', valid: true },
    ],
    sans: [
      { value: '*.acmecorp.io', covered: true },
      { value: 'acmecorp.io', covered: true },
    ],
    ocspStapling: true,
    autoRenewal: true,
    lastScanned: daysAgo(0),
    lastRepaired: null,
  },
  {
    id: 'cert-003',
    domain: 'shop.retailpro.com',
    status: 'healthy',
    provider: 'zerossl',
    server: 'apache',
    challenge: 'http-01',
    isWildcard: false,
    expiresAt: daysFromNow(88),
    issuedAt: daysAgo(2),
    renewsAt: daysFromNow(58),
    daysUntilExpiry: 88,
    chain: [
      { subject: 'shop.retailpro.com', issuer: 'ZeroSSL RSA Domain Secure Site CA', valid: true },
      { subject: 'ZeroSSL RSA Domain Secure Site CA', issuer: 'USERTrust RSA Certification Authority', valid: true },
      { subject: 'USERTrust RSA Certification Authority', issuer: 'USERTrust RSA Certification Authority', valid: true },
    ],
    sans: [
      { value: 'shop.retailpro.com', covered: true },
      { value: 'checkout.retailpro.com', covered: true },
      { value: 'cart.retailpro.com', covered: true },
    ],
    ocspStapling: true,
    autoRenewal: true,
    lastScanned: daysAgo(1),
    lastRepaired: null,
  },
  {
    id: 'cert-004',
    domain: 'dashboard.saasplatform.dev',
    status: 'healthy',
    provider: 'buypass',
    server: 'caddy',
    challenge: 'tls-alpn-01',
    isWildcard: false,
    expiresAt: daysFromNow(160),
    issuedAt: daysAgo(20),
    renewsAt: daysFromNow(130),
    daysUntilExpiry: 160,
    chain: [
      { subject: 'dashboard.saasplatform.dev', issuer: 'Buypass Class 2 CA 5', valid: true },
      { subject: 'Buypass Class 2 CA 5', issuer: 'Buypass Class 2 Root CA', valid: true },
      { subject: 'Buypass Class 2 Root CA', issuer: 'Buypass Class 2 Root CA', valid: true },
    ],
    sans: [
      { value: 'dashboard.saasplatform.dev', covered: true },
      { value: 'app.saasplatform.dev', covered: true },
    ],
    ocspStapling: false,
    autoRenewal: true,
    lastScanned: daysAgo(2),
    lastRepaired: null,
  },
  {
    id: 'cert-005',
    domain: 'auth.fintech-inc.com',
    status: 'healthy',
    provider: 'digicert',
    server: 'haproxy',
    challenge: 'dns-01',
    isWildcard: false,
    expiresAt: daysFromNow(280),
    issuedAt: daysAgo(85),
    renewsAt: daysFromNow(250),
    daysUntilExpiry: 280,
    chain: [
      { subject: 'auth.fintech-inc.com', issuer: 'DigiCert SHA2 Secure Server CA', valid: true },
      { subject: 'DigiCert SHA2 Secure Server CA', issuer: 'DigiCert Global Root CA', valid: true },
      { subject: 'DigiCert Global Root CA', issuer: 'DigiCert Global Root CA', valid: true },
    ],
    sans: [
      { value: 'auth.fintech-inc.com', covered: true },
      { value: 'sso.fintech-inc.com', covered: true },
      { value: 'oauth.fintech-inc.com', covered: true },
    ],
    ocspStapling: true,
    autoRenewal: true,
    lastScanned: daysAgo(1),
    lastRepaired: null,
  },
  {
    id: 'cert-006',
    domain: 'cdn.mediastream.net',
    status: 'healthy',
    provider: 'letsencrypt',
    server: 'traefik',
    challenge: 'dns-01',
    isWildcard: true,
    expiresAt: daysFromNow(44),
    issuedAt: daysAgo(46),
    renewsAt: daysFromNow(14),
    daysUntilExpiry: 44,
    chain: [
      { subject: '*.mediastream.net', issuer: 'R11', valid: true },
      { subject: 'R11', issuer: 'ISRG Root X2', valid: true },
      { subject: 'ISRG Root X2', issuer: 'ISRG Root X2', valid: true },
    ],
    sans: [
      { value: '*.mediastream.net', covered: true },
      { value: 'mediastream.net', covered: true },
    ],
    ocspStapling: true,
    autoRenewal: true,
    lastScanned: daysAgo(0),
    lastRepaired: null,
  },
  {
    id: 'cert-007',
    domain: 'mail.oldcompany.org',
    status: 'expiring-soon',
    provider: 'letsencrypt',
    server: 'nginx',
    challenge: 'http-01',
    isWildcard: false,
    expiresAt: daysFromNow(10),
    issuedAt: daysAgo(80),
    renewsAt: daysFromNow(-20),
    daysUntilExpiry: 10,
    chain: [
      { subject: 'mail.oldcompany.org', issuer: 'R3', valid: true },
      { subject: 'R3', issuer: 'ISRG Root X1', valid: true },
      { subject: 'ISRG Root X1', issuer: 'ISRG Root X1', valid: true },
    ],
    sans: [
      { value: 'mail.oldcompany.org', covered: true },
      { value: 'smtp.oldcompany.org', covered: false },
    ],
    ocspStapling: false,
    autoRenewal: false,
    lastScanned: daysAgo(1),
    lastRepaired: null,
  },
  {
    id: 'cert-008',
    domain: 'api.legacyapp.io',
    status: 'expiring-soon',
    provider: 'zerossl',
    server: 'apache',
    challenge: 'http-01',
    isWildcard: false,
    expiresAt: daysFromNow(6),
    issuedAt: daysAgo(84),
    renewsAt: daysFromNow(-24),
    daysUntilExpiry: 6,
    chain: [
      { subject: 'api.legacyapp.io', issuer: 'ZeroSSL RSA Domain Secure Site CA', valid: true },
      { subject: 'ZeroSSL RSA Domain Secure Site CA', issuer: 'USERTrust RSA Certification Authority', valid: true },
      { subject: 'USERTrust RSA Certification Authority', issuer: 'USERTrust RSA Certification Authority', valid: true },
    ],
    sans: [
      { value: 'api.legacyapp.io', covered: true },
    ],
    ocspStapling: false,
    autoRenewal: false,
    lastScanned: daysAgo(0),
    lastRepaired: null,
  },
  {
    id: 'cert-009',
    domain: 'portal.deadproject.com',
    status: 'expired',
    provider: 'letsencrypt',
    server: 'nginx',
    challenge: 'http-01',
    isWildcard: false,
    expiresAt: daysAgo(5),
    issuedAt: daysAgo(95),
    renewsAt: daysAgo(35),
    daysUntilExpiry: -5,
    chain: [
      { subject: 'portal.deadproject.com', issuer: 'R3', valid: false },
      { subject: 'R3', issuer: 'ISRG Root X1', valid: true },
      { subject: 'ISRG Root X1', issuer: 'ISRG Root X1', valid: true },
    ],
    sans: [
      { value: 'portal.deadproject.com', covered: true },
    ],
    ocspStapling: false,
    autoRenewal: false,
    lastScanned: daysAgo(1),
    lastRepaired: null,
  },
  {
    id: 'cert-010',
    domain: 'internal.corp-tools.net',
    status: 'error',
    provider: 'digicert',
    server: 'nginx',
    challenge: 'dns-01',
    isWildcard: false,
    expiresAt: daysFromNow(120),
    issuedAt: daysAgo(60),
    renewsAt: daysFromNow(90),
    daysUntilExpiry: 120,
    chain: [
      { subject: 'internal.corp-tools.net', issuer: 'DigiCert SHA2 Secure Server CA', valid: true },
      { subject: 'DigiCert SHA2 Secure Server CA', issuer: 'DigiCert Global Root CA', valid: false },
      { subject: 'DigiCert Global Root CA', issuer: 'DigiCert Global Root CA', valid: true },
    ],
    sans: [
      { value: 'internal.corp-tools.net', covered: true },
      { value: 'tools.corp-tools.net', covered: false },
    ],
    ocspStapling: true,
    autoRenewal: true,
    lastScanned: daysAgo(0),
    lastRepaired: daysAgo(3),
  },
  {
    id: 'cert-011',
    domain: 'status.monitoring-hub.io',
    status: 'pending',
    provider: 'letsencrypt',
    server: 'caddy',
    challenge: 'http-01',
    isWildcard: false,
    expiresAt: daysFromNow(0),
    issuedAt: daysAgo(90),
    renewsAt: daysFromNow(-30),
    daysUntilExpiry: 0,
    chain: [],
    sans: [
      { value: 'status.monitoring-hub.io', covered: true },
    ],
    ocspStapling: false,
    autoRenewal: true,
    lastScanned: daysAgo(0),
    lastRepaired: null,
  },
  {
    id: 'cert-012',
    domain: 'payments.ecommercestore.co',
    status: 'error',
    provider: 'zerossl',
    server: 'nginx',
    challenge: 'http-01',
    isWildcard: false,
    expiresAt: daysFromNow(45),
    issuedAt: daysAgo(45),
    renewsAt: daysFromNow(15),
    daysUntilExpiry: 45,
    chain: [
      { subject: 'payments.ecommercestore.co', issuer: 'ZeroSSL RSA Domain Secure Site CA', valid: true },
      { subject: 'ZeroSSL RSA Domain Secure Site CA', issuer: 'USERTrust RSA Certification Authority', valid: true },
      { subject: 'USERTrust RSA Certification Authority', issuer: 'USERTrust RSA Certification Authority', valid: true },
    ],
    sans: [
      { value: 'payments.ecommercestore.co', covered: true },
    ],
    ocspStapling: false,
    autoRenewal: true,
    lastScanned: daysAgo(0),
    lastRepaired: null,
  },
];

export const alerts: Alert[] = [
  {
    id: 'alert-001',
    domain: 'mail.oldcompany.org',
    severity: 'warning',
    message: 'Certificate expires in 10 days. Auto-renewal is disabled.',
    resolvedAt: null,
    createdAt: daysAgo(1),
  },
  {
    id: 'alert-002',
    domain: 'api.legacyapp.io',
    severity: 'error',
    message: 'Certificate expires in 6 days — URGENT renewal required.',
    resolvedAt: null,
    createdAt: daysAgo(0),
  },
  {
    id: 'alert-003',
    domain: 'portal.deadproject.com',
    severity: 'error',
    message: 'Certificate has expired. Site is returning SSL errors.',
    resolvedAt: null,
    createdAt: daysAgo(5),
  },
  {
    id: 'alert-004',
    domain: 'internal.corp-tools.net',
    severity: 'error',
    message: 'Chain validation failed: intermediate CA certificate is untrusted.',
    resolvedAt: null,
    createdAt: daysAgo(2),
  },
  {
    id: 'alert-005',
    domain: 'payments.ecommercestore.co',
    severity: 'warning',
    message: 'OCSP stapling is not configured. Certificate validation may be slower.',
    resolvedAt: null,
    createdAt: daysAgo(1),
  },
  {
    id: 'alert-006',
    domain: 'api.acmecorp.io',
    severity: 'success',
    message: 'Certificate successfully renewed and deployed.',
    resolvedAt: daysAgo(18),
    createdAt: daysAgo(19),
  },
  {
    id: 'alert-007',
    domain: 'status.monitoring-hub.io',
    severity: 'info',
    message: 'Certificate renewal in progress via ACME http-01 challenge.',
    resolvedAt: null,
    createdAt: daysAgo(0),
  },
  {
    id: 'alert-008',
    domain: '*.acmecorp.io',
    severity: 'success',
    message: 'Wildcard certificate renewed and deployed to 3 servers.',
    resolvedAt: daysAgo(35),
    createdAt: daysAgo(36),
  },
  {
    id: 'alert-009',
    domain: 'mail.oldcompany.org',
    severity: 'warning',
    message: 'SAN smtp.oldcompany.org is not covered by current certificate.',
    resolvedAt: null,
    createdAt: daysAgo(3),
  },
  {
    id: 'alert-010',
    domain: 'cdn.mediastream.net',
    severity: 'info',
    message: 'Certificate scheduled for renewal in 14 days.',
    resolvedAt: null,
    createdAt: daysAgo(1),
  },
];

export const renewalJobs: RenewalJob[] = [
  {
    id: 'job-001',
    domain: 'status.monitoring-hub.io',
    status: 'in-progress',
    provider: 'letsencrypt',
    attempt: 1,
    scheduledAt: daysAgo(0),
    startedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    completedAt: null,
    error: null,
  },
  {
    id: 'job-002',
    domain: 'mail.oldcompany.org',
    status: 'queued',
    provider: 'letsencrypt',
    attempt: 1,
    scheduledAt: daysFromNow(0),
    startedAt: null,
    completedAt: null,
    error: null,
  },
  {
    id: 'job-003',
    domain: 'api.legacyapp.io',
    status: 'failed',
    provider: 'zerossl',
    attempt: 3,
    scheduledAt: daysAgo(1),
    startedAt: daysAgo(1),
    completedAt: daysAgo(1),
    error: 'ACME challenge validation failed: http-01 challenge returned 404 at /.well-known/acme-challenge/',
  },
  {
    id: 'job-004',
    domain: 'cdn.mediastream.net',
    status: 'queued',
    provider: 'letsencrypt',
    attempt: 1,
    scheduledAt: daysFromNow(1),
    startedAt: null,
    completedAt: null,
    error: null,
  },
  {
    id: 'job-005',
    domain: 'api.acmecorp.io',
    status: 'completed',
    provider: 'letsencrypt',
    attempt: 1,
    scheduledAt: daysAgo(19),
    startedAt: daysAgo(19),
    completedAt: daysAgo(18),
    error: null,
  },
  {
    id: 'job-006',
    domain: '*.acmecorp.io',
    status: 'completed',
    provider: 'letsencrypt',
    attempt: 1,
    scheduledAt: daysAgo(36),
    startedAt: daysAgo(36),
    completedAt: daysAgo(35),
    error: null,
  },
];

export const fleetStats: FleetStats = {
  total: certificates.length,
  healthy: certificates.filter(c => c.status === 'healthy').length,
  expiringSoon: certificates.filter(c => c.status === 'expiring-soon').length,
  expired: certificates.filter(c => c.status === 'expired').length,
  errors: certificates.filter(c => c.status === 'error').length,
  autoRenewalEnabled: certificates.filter(c => c.autoRenewal).length,
};
